
site_name: My Solana Docs
theme:
    name: mkdocs
    custom_dir: custom_theme/
    logo: img/logo.gif
extra_css:
    - css/extra.css
nav:
    - Home: index.md
    - Whitepaper: whitepaper.md
    - Page 2: page2.md
