site_name: ElysiumX Docs
theme:
    name: mkdocs
    custom_dir: custom_theme/
    logo: img/elysiumx-logo.png
extra_css:
    - css/extra.css
nav:
  - Home: index.md
  - Whitepaper: whitepaper.md
  - Roadmap: roadmap-details.md
  - Security: security-measures.md
  - FAQ: faq.md
  - Getting Started: getting-started.md
  - Community: community-channels.md
